version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm ci --omit=dev --ignore-scripts && npm rebuild bcrypt --build-from-source && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./package-lock.json:/usr/src/clean-node-api/package-lock.json
      - /usr/src/clean-node-api/node_modules/
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
